kanta = float(input("Anna suorakulmion kanta: "))
korkeus = float(input("Anna suorakulmion korkeus: "))
piiri = (kanta * 2) + (korkeus * 2)
ala = (kanta * korkeus)
print(f"Suorakulmion piiri on {piiri:.2f} ja pinta-ala on {ala:.2f}")